version: "3.8"

services:
  mongo:
    container_name: mongo-dev
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE}
    networks:
      - mongo-compose-network
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    command: mongod --config /etc/mongod.conf

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGODB_SERVER}
      - ME_CONFIG_BASICAUTH_USERNAME=${BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_DATABASE=${MONGODB_DATABASE}

    ports:
      - "8081:8081"
    volumes:
      - ./data:/data/db
      - ./wait-for-it.sh:/app/wait-for-it.sh
    command:
      [
        "sh",
        "-c",
        "chmod +x /app/wait-for-it.sh && /app/wait-for-it.sh mongo:27017 -- /docker-entrypoint.sh",
      ]

networks:
  mongo-compose-network:
    driver: bridge
